name: Scheduled Time 
on:
  push:              # Triggers instantly when you push code
  workflow_dispatch: # Allows manual trigger button
  schedule:
    - cron: '*/2 * * * *'

jobs:
  display_time:
    name: Print Server Time
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
